[project]
name = "inflation-rates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fonttools>=4.61.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "plotly>=6.5.1",
    "streamlit>=1.52.2",
    "tqdm>=4.67.1",
]
